Feature   add search functionality
ayushagg31/Trellis pull request #61
Opened 2020-10-27 18:47 UTC by Lutheriel

**Description**
added search functionality

![image](https://user-images.githubusercontent.com/26087661/97347290-def4b800-188c-11eb-8b8b-58613fd3c2f0.png)
![image](https://user-images.githubusercontent.com/26087661/97347259-d2705f80-188c-11eb-9dde-b3501fcaf634.png)

**Fixes** # (issue reference)
https://github.com/ayushagg31/Trellis/issues/14

**Type of change**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Checklist**
- [x ] I have read the [Contribution Guidelines](https://github.com/ayushagg31/Trellis/blob/master/CONTRIBUTING.md)
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream module

2020-10-28 04:25 UTC, ayushagg31 commented
You have added functionality to search among the cards. Please add alert/msg for user when card is not found. Also replace the `Search` placeholder with appropriate text. Also, if possible add a highlight background in search text for user feasibility. Rest looks good, I'll review it in details later. 
Thanks for the contribution 😄

2020-10-29 05:31 UTC, ayushagg31 requested changes

2020-10-31 23:01 UTC, Lutheriel commented
added highlighting, new placeholder and alert. 
![image](https://user-images.githubusercontent.com/26087661/97791676-41bfb980-1bd5-11eb-8739-8a5138a60973.png)
![image](https://user-images.githubusercontent.com/26087661/97791684-57cd7a00-1bd5-11eb-8b43-f353092a5a68.png)
![image](https://user-images.githubusercontent.com/26087661/97791689-5d2ac480-1bd5-11eb-9a4e-f488be8121f1.png)

2020-11-02 05:46 UTC, ayushagg31 approved these changes

2020-11-02 05:47 UTC, merged